In [ ]:
#numpy

In [ ]:
import numpy as np
print("hello world")

hello world


In [ ]:
myarr = np.array([[1,2,3]])
myarr[0]

array([1, 2, 3])

In [ ]:
myarr.shape

(1, 3)

In [ ]:
import numpy as np # with tuple
my_arr=np.array((12,3,5,58))
my_arr


array([12,  3,  5, 58])

In [ ]:
#0-D arrays
import numpy as np
arr=np.array(34)
arr

array(34)

In [ ]:
# 1-D array
import numpy as np 
arr=np.array([12,3,4])
arr

array([12,  3,  4])

In [ ]:
#2-D array array that has 1d element is called 2d array
arr=np.array([[12,3,4],[34,6,7]])
arr


array([[12,  3,  4],
       [34,  6,  7]])

In [ ]:
#3d arrayy it has  2d array element called 3d array
import numpy as np
arr=np.array([[[1,3,4],[7,6,7]],[[12,5,6],[5,6,7]]])
arr

array([[[ 1,  3,  4],
        [ 7,  6,  7]],

       [[12,  5,  6],
        [ 5,  6,  7]]])

In [ ]:
import numpy as np
a=np.array(45)
b=np.array([12,34,57])
c=np.array([[13,67,88],[7,8,9]])
d=np.array([[[12,45,77],[45,89,78]],[[45,78,65],[34,98,17]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [2]:
import numpy as np
b=np.array([12,34,57],ndmin=5)
print(b)

print('no of dimention',b.ndim)

[[[[[12 34 57]]]]]
no of dimention 5


In [ ]:
arrr=np.arange(50)
arr